# Generated by Django 5.0.3 on 2024-11-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_remove_landmark_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('total', models.IntegerField()),
                ('users', models.JSONField()),
                ('journal', models.JSONField()),
            ],
        ),
    ]
