# Generated by Django 5.0.3 on 2024-11-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('routeid', models.CharField(max_length=2048)),
                ('routearray', models.JSONField()),
                ('average', models.FloatField()),
                ('total', models.IntegerField()),
                ('journal', models.JSONField()),
                ('users', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('reviews', models.JSONField()),
            ],
        ),
    ]
