# Generated by Django 5.0.3 on 2024-11-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_route_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reviews',
            new_name='routes',
        ),
    ]
