# Generated by Django 5.0.3 on 2024-11-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_landmark_latitude_landmark_longitude'),
        ('tours', '0005_rename_reviews_user_routes'),
    ]

    operations = [
    ]
